In [1]:
import numpy as np
import pandas as pd

/Users/tusharkaushik/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
df = pd.read_csv('customer.csv')

In [3]:
df.sample(5)

    age  gender   review education purchased
21   32    Male  Average        PG        No
42   30  Female     Good        PG       Yes
45   61    Male     Poor        PG       Yes
6    18    Male     Good    School        No
22   18  Female     Poor        PG       Yes

In [8]:
df['gender'].unique()

array(['Female', 'Male'], dtype=object)

In [9]:
df['review'].unique()

array(['Average', 'Poor', 'Good'], dtype=object)

In [10]:
df['education'].unique()

array(['School', 'UG', 'PG'], dtype=object)

In [11]:
df['purchased'].unique()

array(['No', 'Yes'], dtype=object)

In [12]:
#For ordinal variables in the input, we have ordinal encoder
#For catagorical variables in the output, we have label encoder

#We will use ordinal encoder for the inputs review and education since order exists in the values and 
#One hot encoding for age and purchased columns

In [13]:
df = df.iloc[:,2:]

In [14]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1], test_size=0.2)

In [19]:
from sklearn.preprocessing import OrdinalEncoder

In [20]:
X_train

     review education
15     Poor        UG
43     Poor        PG
44  Average        UG
1      Poor        UG
30  Average        UG
3      Good        PG
20  Average    School
25     Good    School
45     Poor        PG
22     Poor        PG
12     Poor    School
32  Average        UG
7      Poor    School
11     Good        UG
49     Good        UG
41     Good        PG
17     Poor        UG
5   Average    School
6      Good    School
37  Average        PG
18     Good    School
13  Average    School
0   Average    School
9      Good        UG
35     Poor    School
34  Average    School
23     Good    School
27     Poor        PG
31     Poor    School
38     Good    School
21  Average        PG
10     Good        UG
46     Poor        PG
4   Average        UG
48     Good        UG
26     Poor        PG
24  Average        PG
36     Good        UG
47     Good        PG
40     Good    School

In [21]:
#Passing the catagories values in order
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [22]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [23]:
X_train = oe.transform(X_train)

In [24]:
X_train

array([[0., 1.],
       [0., 2.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [2., 2.],
       [1., 0.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [2., 1.],
       [2., 1.],
       [2., 2.],
       [0., 1.],
       [1., 0.],
       [2., 0.],
       [1., 2.],
       [2., 0.],
       [1., 0.],
       [1., 0.],
       [2., 1.],
       [0., 0.],
       [1., 0.],
       [2., 0.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [1., 2.],
       [2., 1.],
       [0., 2.],
       [1., 1.],
       [2., 1.],
       [0., 2.],
       [1., 2.],
       [2., 1.],
       [2., 2.],
       [2., 0.]])

In [25]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [26]:
X_train

array([[0., 1.],
       [0., 2.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [2., 2.],
       [1., 0.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [2., 1.],
       [2., 1.],
       [2., 2.],
       [0., 1.],
       [1., 0.],
       [2., 0.],
       [1., 2.],
       [2., 0.],
       [1., 0.],
       [1., 0.],
       [2., 1.],
       [0., 0.],
       [1., 0.],
       [2., 0.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [1., 2.],
       [2., 1.],
       [0., 2.],
       [1., 1.],
       [2., 1.],
       [0., 2.],
       [1., 2.],
       [2., 1.],
       [2., 2.],
       [2., 0.]])

In [27]:
#Label encoding the output var
from sklearn.preprocessing import LabelEncoder

In [28]:
le = LabelEncoder()

In [29]:
le.fit(y_train)

LabelEncoder()

In [30]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [31]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [32]:
y_train

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0])

# One Hot Encoding using Pandas

In [33]:
df = pd.read_csv('cars.csv')

In [34]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [35]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [37]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [36]:
#we use func get_dummies and pass the df name and list of cols we want to use
#no of columns in new dataframe will be 2 less than the oroginal 

#We will get 4 new cols for fuel and 5 new columns for owner

pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

In [38]:
#ONE HOT ENCODING DOES NOT SOLVE THE PROBLEM OF MULTICOLLINEARITY

# 2. K-1 OneHotEncoding

In [39]:
#TO SOLVE MULTICOLLINEARITY, WE USE drop_first
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

In [40]:
#WE DO NOT USE PANDAS FOR ML PROJECT as it does not remember the position of columns
#We use pandas for one hot encoding only for the analysis
#We use one hot encoder class instead in sklearn

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)

In [42]:
X_train.head()

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [43]:
X_test.head()

         brand  km_driven    fuel         owner
606    Hyundai      80000  Petrol   First Owner
7575  Mahindra      70000  Diesel  Second Owner
7705    Toyota      68089  Petrol   First Owner
4305   Hyundai      70000  Petrol  Second Owner
2685  Mahindra      97000  Diesel  Second Owner

In [44]:
from sklearn.preprocessing import OneHotEncoder

In [51]:
#we want to apply one hot encoding only on fuel and owner
#we extract these 2 ols and then append to other cols > sol is column transform

ohe = OneHotEncoder(drop='first')

In [52]:
X_train_new = ohe.fit_transform(X_train[['fuel', 'owner']])

In [53]:
X_test_new = ohe.transform(X_test[['fuel', 'owner']])

In [54]:
X_train_new.shape

(6502, 7)

In [56]:
print(X_train_new.shape, X_test_new.shape)

(6502, 7) (1626, 7)

In [58]:
# Concatenate brand and km_driven columns with the encoded features (X_train_new)
X_train_concat = np.hstack((X_train[['brand', 'km_driven']].values, X_train_new.toarray()))

# Similarly, concatenate for X_test
X_test_concat = np.hstack((X_test[['brand', 'km_driven']].values, X_test_new.toarray()))

# 4. OneHotEncoding with Top Categories

In [59]:
counts = df['brand'].value_counts()

In [60]:
df['brand'].nunique()
threshold = 100

In [61]:
repl = counts[counts <= threshold].index

In [62]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
2080,False,False,False,False,False,False,False,False,False,True,False,False,False
2150,False,True,False,False,False,False,False,False,False,False,False,False,False
2707,False,False,False,False,False,False,False,False,False,False,True,False,False
2135,False,False,False,False,False,False,False,False,False,False,False,False,True
1399,False,False,False,False,False,False,False,False,False,False,True,False,False

In [64]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [65]:
df = pd.read_csv('covid_toy.csv')

In [66]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [67]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [69]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [70]:
#one hot encoding on gender and has cough, cause they are 
#nominal encoding on fever and cough

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [71]:
X_train

    age  gender  fever   cough       city
57   49  Female   99.0  Strong  Bangalore
61   81  Female   98.0  Strong     Mumbai
30   15    Male  101.0    Mild      Delhi
96   51  Female  101.0  Strong    Kolkata
48   66    Male   99.0  Strong  Bangalore
..  ...     ...    ...     ...        ...
4    65  Female  101.0    Mild     Mumbai
78   11    Male  100.0    Mild  Bangalore
59    6  Female  104.0    Mild    Kolkata
64   42    Male  104.0    Mild     Mumbai
99   10  Female   98.0  Strong    Kolkata

[80 rows x 5 columns]

# !Without using column transformer

In [72]:
# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])
                                 
X_train_fever.shape

(80, 1)

In [73]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [83]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first',sparse=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'sparse'

In [80]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Initialize OneHotEncoder without sparse argument
ohe = OneHotEncoder(drop='first')

# Fit-transform on training data
X_train_encoded = ohe.fit_transform(X_train[['gender', 'city']])

# Convert sparse matrix to dense array
X_train_encoded = X_train_encoded.toarray()

# Now X_train_encoded is a dense array
X_train_encoded.shape

(80, 4)

In [78]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [84]:
from sklearn.compose import ColumnTransformer